[server]
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "light"

[logger]
level = "info"
messageFormat = "%(asctime)s.%(msecs)03d %(name)s: %(levelname)s: %(message)s"
dateFormat = "%Y-%m-%d %H:%M:%S"

[client]
showSidebarNavigation = true

# Development vs Production settings
[development]
[browser.server]
port = 8501

[browser.gatherUsageStats]
enabled = false
